### ISSUE TITLE
Excludes with '-R' don't seem to work

### ISSUE THREAD

**Issue by otraupe** [zfsnap/zfsnap.org#1]
Downloaded the zfsnap_master today and find that it works very well!

Only one thing: the -R option is not working for me.

I have a pool 'data' and various nested data sets up to the level three: e.g. data/home/user. All are snapshotted. I would only like to exclude data/backup. I use this command:

/usr/local/sbin/zfsnap snapshot -p zfsnap_ -v -a 12d -r data -R data/backup >> /var/log/zfsnap.log

The set 'data/backup' also gets a snapshot. At least a browsable directory under .zfs/snapshot is created with the respective time stamp.

EDIT: Right, sorry. Also I saw that I misread the manual. Can you delete this entry?

**Comment by graudeejs** [comment]
Wrong project. You wanted to report here:
https://github.com/zfsnap/zfsnap/issues

Please report there
